version: "2"
services:
  redis-test:
    image: redis:3.2

  postgres-test:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: insapi-test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./backups:/backups
      - /applis/insapi/home/postgresql-test:/var/lib/postgresql/data/pgdata
  server:
    image: node:8.12.0
    volumes:
      - .:/app
    working_dir: /app
    environment:
      NODE_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: insapi-test
      POSTGRES_HOST: postgres-test
    depends_on:
      - redis-test
      - postgres-test
      - maildev-test
    links:
      - redis-test
      - postgres-test
      - maildev-test
    command: node_modules/mocha/bin/mocha test/mocha test/mocha/**/*.js
  maildev-test:
    image: djfarrelly/maildev
    ports:
      - 1081:80
