version: "3.5"

services:
  postgres-prod:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: insapi-prod
    volumes:
      - ./backups:/backups
      - /applis/insapi/home/postgresql:/var/lib/postgresql/data
    networks:
      - insbackend
  
  ins-server:
    image: vsnexus-registry.intra.inist.fr:8083/insermbiblio/insapi:${insapi_version}
    volumes:
      - ./logs:/app/logs
      - ./imports:/app/imports
    environment:
      NODE_ENV: ${NODE_ENV}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      header_secret: ${header_secret}
      cookie_secret: ${cookie_secret}
      admin_secret: ${admin_secret}
      ticket_secret: ${ticket_secret}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: insapi-prod
      POSTGRES_HOST: postgres-prod
      MAIL_SERVER_HOST: ${MAIL_SERVER_HOST}
      MAIL_SERVER_PORT: ${MAIL_SERVER_PORT}
    ports:
      - 3000:3000
    restart: always
    command: node launcher.js
    networks:
      - insbackend
      - insfrontend

networks:
  insbackend:
    external: true
  insfrontend:
    external: true