version: "3.5"

services:
  postgres-dev:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: insapi-dev
    volumes:
      - ./backups:/backups
      - ../postgresql-dev:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - insbackend
  
  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - insbackend

  ins-server:
    image: node:8.12.0
    volumes:
      - .:/app
    working_dir: /app
    environment:
      NODE_ENV: development
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: insapi-dev
      POSTGRES_HOST: postgres-dev
    ports:
      - 3000:3000
    command: npm run dev
    networks:
      - insbackend
      - insfrontend

  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80
    networks:
      - insbackend

networks:
  insbackend:
    external: true
  insfrontend:
    external: true