version: "3.5"

services:
  npm:
    image: node:8.12.0
    volumes:
      - .:/app
    working_dir: /app
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: "localhost,127.0.0.1,"
    entrypoint: ["npm"]
    networks:
      - insbackend
  server:
    image: node:8.12.0
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: node launcher.js
    networks:
      - insbackend

networks:
  insbackend:
    driver: bridge
    name : insbackend
